// 손으로 찍은 16x16 픽셀 아이콘 (도구 / 지도 POI)
import { spriteFromRows, makeCanvas } from './util.js';

export const PAL = {
  k: '#101018', K: '#2c2c3a', w: '#f4f4f0', g: '#a8adb8', G: '#5d6474',
  r: '#e0453c', R: '#8e2226', y: '#f5cc48', Y: '#b58a2a', o: '#f08a2e',
  b: '#4a86d8', B: '#24457a', c: '#8fd8f2', n: '#9a6a3c', N: '#5c3b20',
  e: '#62c04e', E: '#2e7a36', s: '#f1c9a0', p: '#e27bb0', v: '#8a55c7',
};

const ICONS = {
  telescope: [
    '................',
    '............kkk.',
    '..........kkcbbk',
    '........kkbbbbBk',
    '......kkbbbbbBk.',
    '....kkybbbbBBk..',
    '...kyyykbbBBk...',
    '..kyYYk.kBBk....',
    '.kwYk....kk.....',
    '.kkk...kk.......',
    '......k.k.k.....',
    '.....k..k..k....',
    '....k...k...k...',
    '...k....k....k..',
    '..kk...kk...kk..',
    '................',
  ],
  phone: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..krrrrrrrrrrk..',
    '.krrRkkkkkkRrrk.',
    '.krRk......kRrk.',
    '.kkk........kkk.',
    '................',
    '....kkkkkkkk....',
    '...krrrrrrrrk...',
    '..krrwkwkwkrrk..',
    '..krrkwkwkwrrk..',
    '..krrwkwkwkrrk..',
    '..kRRRRRRRRRRk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  sns: [
    '................',
    '....kkkkkkkkk...',
    '...kKKKKKKKKKk..',
    '...kKcccccccKk..',
    '...kKcrrcrrcKk..',
    '...kKrrrrrrrKk..',
    '...kKcrrrrrcKk..',
    '...kKccrrrccKk..',
    '...kKcccrcccKk..',
    '...kKcccccccKk..',
    '...kKcwwwwwcKk..',
    '...kKcgggggcKk..',
    '...kKcccccccKk..',
    '...kKKKKKKKKKk..',
    '...kKKKKwKKKKk..',
    '....kkkkkkkkk...',
  ],
  hack: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kKKKKKKKKKKk..',
    '..kKeekeeekkKk..',
    '..kKkeeekeekKk..',
    '..kKeekkeeeeKk..',
    '..kKkeekkkkkKk..',
    '..kKeekwkkkkKk..',
    '..kKKKKKKKKKKk..',
    '.kggggggggggggk.',
    'kgGgGgGgGgGgGggk',
    'kggggggggggggggk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  notebook: [
    '................',
    '...kkkkkkkkkk...',
    '..gkwwwwwwwwwk..',
    '...kwggggggwwk..',
    '..gkwwwwwwwwwk..',
    '...kwgggggwwwk..',
    '..gkwwwwwwwwwk..',
    '...kwgggggggwk..',
    '..gkwwwwwwwwwk..',
    '...kwggggwwwwk..',
    '..gkwwwwwwwwwk..',
    '...kwwwwwwwrwk..',
    '..gkwwwwwwrrwk..',
    '...kwwwwwwwwwk..',
    '...kkkkkkkkkkk..',
    '................',
  ],
  dossier: [
    '................',
    '................',
    '.kkkkkk.........',
    'kYYYYYYk........',
    'kYYYYYYYkkkkkkk.',
    'kyyyyyyyyyyyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyyyrrrrrrrryyyk',
    'kyyyrwwwwwwryyyk',
    'kyyyrrrrrrrryyyk',
    'kyyyyyyyyyyyyyyk',
    'kyykkkkkyyyyyyyk',
    'kyyyyyyyyyyyyyyk',
    'kyykkkkkkkkyyyyk',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  globe: [
    '................',
    '.....kkkkkk.....',
    '...kkbbeebbkk...',
    '..kbbeeeebbbbk..',
    '.kbbbeeeebbbbbk.',
    '.kbbbbeebbbeebk.',
    'kbbbbbeebbeeeebk',
    'kbbbbbbbbbeeeebk',
    'kbbbbbbbbbbeeebk',
    'kbbeebbbbbbeebbk',
    'kbeeeebbbbbbbbbk',
    '.kbeeeebbbbbbbk.',
    '.kbbeeebbbbbbbk.',
    '..kbbeebbbbbbk..',
    '...kkbbbbbbkk...',
    '.....kkkkkk.....',
  ],
  back: [
    '................',
    '................',
    '......kk........',
    '.....kyk........',
    '....kyyk........',
    '...kyyykkkkkkk..',
    '..kyyyyyyyyyyyk.',
    '.kyyyyyyyyyyyyk.',
    '..kyyyyyyyyyyyk.',
    '...kyyykkkkkkk..',
    '....kyyk........',
    '.....kyk........',
    '......kk........',
    '................',
    '................',
    '................',
  ],
  plane: [
    '................',
    '.......kk.......',
    '......kwwk......',
    '......kwwk......',
    '......kwwk......',
    '.....kwwwwk.....',
    '...kkwwwwwwkk...',
    '.kkwwwwwwwwwwkk.',
    'kwwwwgwwwwgwwwwk',
    '.kkkkkwwwwkkkkk.',
    '......kwwk......',
    '......kwwk......',
    '.....kwwwwk.....',
    '....kwwkkwwk....',
    '....kkk..kkk....',
    '................',
  ],
  pin: [
    '....kkkkk.......',
    '...krrrrrk......',
    '..krrwwrrrk.....',
    '..krwwrrrrk.....',
    '..krrrrrrRk.....',
    '..krrrrrRRk.....',
    '...krrrRRk......',
    '....krRRk.......',
    '.....kRk........',
    '.....kRk........',
    '......k.........',
  ],
  // ---- 지도 POI ----
  city: [
    '................',
    '..........kkk...',
    '..........kck...',
    '....kkk...kbk...',
    '....kck..kkbkk..',
    '....kbk..kcbck..',
    '..kkkbkkkkbbbk..',
    '..kcbcbkkcbcbk..',
    '..kbbbbkkbbbbkkk',
    '..kcbcbkkcbcbkck',
    'kkkbbbbkkbbbbkbk',
    'kckcbcbkkcbcbkck',
    'kbkbbbbkkbbbbkbk',
    'kckcbcbkkcbcbkck',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  mountain: [
    '................',
    '................',
    '.......k........',
    '......kwk.......',
    '.....kwwwk......',
    '.....kwgwwk.....',
    '....kgkwgGk.k...',
    '...kGggGGGGkwk..',
    '...kgGGGGGGGkwk.',
    '..kgGGGGGGGGGkGk',
    '.kgGGGGGGGGGGGGk',
    'kggGGGGGGGGGGGGk',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
    '................',
  ],
  beach: [
    '................',
    '......kkkk......',
    '....kkrwrwkk....',
    '...krwrwrwrwk...',
    '..krwrwrwrwrwk..',
    '..kkkkkkkkkkkk..',
    '.......kN.......',
    '.......kN.......',
    '.......kN.......',
    '......kkNk......',
    'bbccbbbccbbbccbb',
    'bbbbbbbbbbbbbbbb',
    'yyyyyyyyyyyyyyyy',
    'yyYyyyyyYyyyyyYy',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  factory: [
    '...gg...........',
    '..gggg..........',
    '...gg...........',
    '...kk...........',
    '...kRk..........',
    '...kwk...k...k..',
    '...kRk..kGk.kGk.',
    '...kwk.kGGkkGGk.',
    '...kRkkGGGGGGGk.',
    '..kGGGGGGGGGGGk.',
    '..kGyGGyGGyGGGk.',
    '..kGGGGGGGGGGGk.',
    '..kGyGGyGGkkkGk.',
    '..kGGGGGGGkNkGk.',
    '..kkkkkkkkkkkkk.',
    '................',
  ],
  station: [
    '................',
    '...kkkkkkkkkk...',
    '..kEEEEEEEEEEk..',
    '..kEccEEEEccEk..',
    '..kEccEEEEccEk..',
    '..kEEEEEEEEEEk..',
    '..kyyyyyyyyyyk..',
    '..kEEEEEEEEEEk..',
    '..kEwEEEEEEwEk..',
    '..kEEEEEEEEEEk..',
    '...kkkkkkkkkk...',
    '....kk....kk....',
    'gggggggggggggggg',
    'NgNNgNNgNNgNNgNN',
    'gggggggggggggggg',
    '................',
  ],
  launch: [
    '.......kk.......',
    '......kwwk......',
    '......kwwk......',
    '.....kwwwwk.....',
    '.....kwrrwk.....',
    '.....kwwwwk.....',
    '.....kwwwwk.....',
    '.....kwbbwk.....',
    '.....kwwwwk.....',
    '....kwwwwwwk....',
    '...kwkwwwwkwk...',
    '...kk.kyyk.kk...',
    '......yooy......',
    '.....oyyyyo.....',
    '....o.oyyo.o....',
    '................',
  ],
  ski: [
    '................',
    '..........k.....',
    '.........kek....',
    '....k....kek....',
    '...kek..keeek...',
    '...kek..keeek...',
    '..keeek.keeek...',
    '..keeek..kNk....',
    '...kNk...kNk....',
    '............kccw',
    '.........kkcwwww',
    '......kkcwwwwwww',
    '...kkcwwwwwwwwww',
    'kkcwwwwwwwwwwwww',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  landmark: [
    '.......rr.......',
    '......royr......',
    '.......kk.......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '......kwgk......',
    '.....kwwggk.....',
    '.....kwwggk.....',
    '....kwwwgggk....',
    '...kkkkkkkkkk...',
    '...kgggggggGk...',
    '..kkkkkkkkkkkk..',
    '..kggggggggggGk.',
    '..kkkkkkkkkkkkk.',
  ],
  village: [
    '................',
    '................',
    '......kkkk......',
    '.....kRRRRk.....',
    '....kRRRRRRk....',
    '...kRRRRRRRRk...',
    '..kRRRRRRRRRRk..',
    '.kkkkkkkkkkkkkk.',
    '..kyyyyyyyyyyk..',
    '..kykkykNNNNyk..',
    '..kykcykNNNNyk..',
    '..kykkykNNNNyk..',
    '..kyyyyyNNNNyk..',
    '..kkkkkkkkkkkk..',
    '.eeEeeEeeEeeEee.',
    '................',
  ],
  jsa: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kbbbbbbbbbbbbk.',
    'kbbbbbbbbbbbbbbk',
    'kkkkkkkkkkkkkkkk',
    '.kbbbbbbbbbbbbk.',
    '.kbwwbbbbbbwwbk.',
    '.kbwwbbbbbbwwbk.',
    '.kbbbbbkkbbbbbk.',
    '.kbbbbbkkbbbbbk.',
    'gggggggggggggggg',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  star: [
    '...k...',
    '..kyk..',
    'kkkyykk',
    'kyyyyyk',
    '.kyyyk.',
    '.kykyk.',
    '.kk.kk.',
  ],
};

export const ICON = {};
export function initArt() {
  for (const [k, rows] of Object.entries(ICONS)) ICON[k] = spriteFromRows(rows, PAL);
  // 수도 아이콘 = 도시 + 별
  const [c, x] = makeCanvas(16, 16);
  x.drawImage(ICON.city, 0, 0);
  x.drawImage(ICON.star, 0, 0);
  ICON.capital = c;
}
export function iconDataURL(name, scale = 3) {
  const src = ICON[name];
  const [c, x] = makeCanvas(src.width * scale, src.height * scale);
  x.drawImage(src, 0, 0, c.width, c.height);
  return c.toDataURL();
}
